name: docker-streamlit-ollama
services:
  streamlit:
    image: python:3.12.7-slim
    networks:
      - internal-net
    ports:
      - '8501:8501'
    volumes:
      - ./src:/src
      - python-deps:/root/.cache/pip
    working_dir: /src
    command: bash -c "pip install -r requirements.txt && streamlit run app.py"
    restart: unless-stopped

  ollama:
    image: "ollama/ollama" #use the latest image
    networks:
      - internal-net
    volumes:
      - ollama_models:/root/.ollama/models / #specify a directory to store models
      - ./ollama-backend/modelfiles:/modelfiles #target project_dir/models for custom model files
    ports:
      - "11434:11434"

networks:
  internal-net:
    driver: bridge

volumes:
  python-deps: {}
  ollama_models: {}