MONGODB_URI = 'mongodb+srv://damonngkhaiweng:jhT8LGE0qi6XsKfz@chatbotcluster.noyfa.mongodb.net/?retryWrites=true&w=majority&appName=chatbotcluster'
MONGODB_DB = 'product1Chunked'
MONGODB_RAG_COLLECTION = 'llamaIndexChunks'
EXTERNAL_OLLAMA_API_URL = "https://protofaze--llama-ptfz-fastapi-app.modal.run"
EXTERNAL_OLLAMA_API_KEY = 'default'
GOOGLE_APPLICATION_CREDENTIALS = 'default'
LLAMA_PARSE_API_KEY = 'llx-k732fOWTc0QlNnIJDxpkB1P0jj4cNr4EIXFgaD7VkwNF9mTb'
ADMIN_PASSWORD = '12345'
IS_ADMIN = false
MODEL = 'C3'