name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy job
        run: |
          cd ollama_backend
          modal run ollama_backend.py
          modal deploy ollama_backend.py
